<?php
// Auto Setup Script for UKK Wiene2
// This script will detect your environment (Local or Cloud) and setup the database.

require_once 'config/database.php';

echo "<style>body { font-family: sans-serif; line-height: 1.6; padding: 20px; color: #333; } .success { color: green; } .info { color: blue; } .error { color: red; }</style>";
echo "<h1>🚀 UKK SIPESKU Auto-Setup</h1>";
echo "<p>Environment: <b>" . (env('MYSQLHOST') ? 'Cloud (Vercel/Aiven)' : 'Localhost') . "</b></p>";
echo "<p>Host: <b>" . DB_HOST . "</b></p>";

try {
    // Note: $db is already instantiated in config/database.php
    echo "<p class='success'>✅ 1. Connected to Database Server.</p>";

    // 2. Import SQL if tables missing
    $stmt = $db->query("SHOW TABLES LIKE 'admin'");
    if (!$stmt->fetchColumn()) {
        echo "<p>Tables missing. Importing structure...</p>";
        
        $sql_file = __DIR__ . '/config/database.sql';
        if (file_exists($sql_file)) {
            $sql = file_get_contents($sql_file);
            
            // Execute the SQL dump
            // Note: For managed DBs like Aiven, we omit CREATE DATABASE/USE commands
            // we assume the DB is already selected in the DSN
            $db->exec($sql);
            echo "<p class='success'>✅ 2. Database structure imported from 'config/database.sql'.</p>";
        } else {
             echo "<p class='error'>❌ ERROR: 'config/database.sql' file not found!</p>";
             exit;
        }
    } else {
        echo "<p class='info'>ℹ️ 2. Tables already exist (Skipping import).</p>";
    }

    // 3. Verify Admin Account
    $stmt = $db->query("SELECT COUNT(*) FROM admin WHERE username='admin'");
    if (!$stmt->fetchColumn()) {
        $pass_hash = md5('user123');
        $stmt = $db->prepare("INSERT INTO admin (username, password) VALUES ('admin', ?)");
        $stmt->execute([$pass_hash]);
        echo "<p class='success'>✅ 3. Default Admin account created (admin / user123).</p>";
    } else {
        echo "<p class='info'>ℹ️ 3. Admin account already exists.</p>";
    }

    // 4. Verify Student Account (Dummy)
    $stmt = $db->query("SELECT COUNT(*) FROM siswa");
    if (!$stmt->fetchColumn()) {
        $pass_hash = md5('user123');
        $stmt = $db->prepare("INSERT INTO siswa (nisn, nama, kelas, password) VALUES (?, ?, ?, ?)");
        $stmt->execute(['12345', 'Siswa Demo', 'XII RPL 1', $pass_hash]);
        echo "<p class='success'>✅ 4. Demo Student account created (12345 / user123).</p>";
    } else {
        echo "<p class='info'>ℹ️ 4. Student accounts already exist.</p>";
    }

    echo "<h2>🏆 Setup Complete!</h2>";
    echo "<p><a href='index.php'>Go to Login Page</a></p>";

} catch (PDOException $e) {
    echo "<h3 class='error'>❌ Setup Failed: " . $e->getMessage() . "</h3>";
    echo "<p>Check your Environment Variables in Vercel if this is a cloud deployment.</p>";
}
echo "<hr><p><small>Generated by Antigravity</small></p>";
